name = "UnitfulDual"
uuid = "fee60b8e-b2b3-11e9-0afc-65d21ea4278f"
authors = ["Alejandro Morales Sierra"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
